CREATE TABLE vegetables (
	id INTEGER,
	name TEXT,
	shape TEXT,
	amount_in_stock INTEGER,
	colour TEXT,
	descriptor TEXT
) ;

--The above SQL was generated by DBeaver when the 'vegetables' table was created.

INSERT INTO vegetables
(id, name, shape, amount_in_stock, colour, descriptor)
VALUES(1,'carrot','cone',25,'orange','for beta carotene');

INSERT INTO vegetables
(id, name, shape, amount_in_stock, colour, descriptor)
VALUES(2,'beans','kidney',33,'green','for fibre');

INSERT INTO vegetables
(id, name, shape, amount_in_stock, colour, descriptor)
VALUES(3,'tomato','sphere',14,'red','for vitamin C');

--The insert statements above were made to generate data to put into the table.

SELECT * FROM vegetables;--the * is a shortcut for selecting all columns.
